name: Update Roblox Key Every Hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-key:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate random key
        id: generate
        run: |
          NEW_KEY=$(openssl rand -hex 12 | tr '[:lower:]' '[:upper:]')
          echo "key=$NEW_KEY" >> $GITHUB_OUTPUT

      - name: Save key to file
        run: echo "${{ steps.generate.outputs.key }}" > current_key.txt

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add current_key.txt
          git commit -m "🔑 Новый ключ: ${{ steps.generate.outputs.key }}"
          git pull --rebase origin main
          git push
